### ISSUE TITLE
Instagram: Create Instastories about ways to contribute

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-pride#2]
## Contributor Instastories 
Contributing to open source software can be fun and sharing what we're doing with the community is just as important than the code we're writing. Would love to encourage non-programmers to engage in open source through areas in which they already know. 

Take a look at [All-Contributors key](https://allcontributors.org/docs/en/emoji-key) for contributions as inspiration. I think there's so much more our community does that I want to honor and recognize, but this would give us a great start. 🎉

**Comment by mehnazyunus** [comment]
Hi, what work does this issue expect?

**Comment by madiedgar** [comment]
Hey @mehnazyunus, so this issue is to be a little fun and creative! This issue would entain creating instastories through whatever medium you're comfortable with (whether it be photoshop or canva or saving a created image on instagram) and adding the story photos to a folder in this repo. 

I'll add in the **Legesher** branding guidelines so you the content you create aligns with the branding of the project.

Would this be something you're interested in?
