### ISSUE TITLE
profile link broken

### ISSUE THREAD

**Issue by onFilm** [legesher/legesher-pride#23]
**Describe the bug**
Clicking on User profile jaywahr link on README.md takes to GitHub 404 error page

**To Reproduce**
1. Go to 'README.md'
2. Scroll down to 'the-community' section
3. Click on 'jaywahr'

**Expected behavior**
GitHub user's profile page should display.

**Comment by madiedgar** [comment]
Thanks for opening this @onFilm! Closing now that your PR #24 was merged 🎉
