### ISSUE TITLE
Add Contributing Section to README

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-pride#8]
## Add Contributing Section to the README.md File

You'll need to add the following code after the "Welcome" section but before the "Legesher Projects" section  (though not in markdown quote but with the same style) :

># Contributing
>❤️Legesher relies on the passionate members of its community (both developer and non-developer alike) to keep delivering impactful tools to people all over the world.
>  
>Before contributing, be sure to consult Legesher's [contribution guidelines](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md) and [language conventions](https://github.com/legesher/legesher/blob/master/LANGUAGE_CONVENTIONS.md). As a member of our community, you must abide by our [Code Of Conduct](https://github.com/legesher/legesher/blob/master/CODE_OF_CONDUCT.md).

See [this](https://github.com/legesher/legesher-docs#contributing) for reference

**Comment by pablostellet** [comment]
Hi can I help you on it?

**Comment by madiedgar** [comment]
Absolutely @pablostellet! Would love your help!

**Comment by nmpatel347** [comment]
can i help you regarding this?

**Comment by jaywahr** [comment]
@madiedgar has anyone started work on this? Would love to to contribute, being new to open source.

**Comment by jaywahr** [comment]
@madiedgar has this been resolved with your PR here? https://github.com/legesher/legesher/pull/66

**Comment by madiedgar** [comment]
Hey @jaywahr 👋 Yes this issue was resolved in the `legesher/legesher` repo, but the same changes need to be made in every repo to maintain consistency. With that being said, I've updated the issue description as this README didn't have a **Contributing** section. Would love your help on this!

**Comment by jaywahr** [comment]
@madiedgar added pull request #9

**Comment by jaywahr** [comment]
@madiedgar does this need to be closed to count toward Hacktoberfest?

**Comment by madiedgar** [comment]
Hey @jaywahr 👋, I believe with the Hacktoberfest guidelines it's just the pull request that needs to be made. I'll close this however, as #9 resolved this issue.
